# Source: https://github.com/bitnami/containers/tree/main/bitnami/spark#readme

services:
  spark-master:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      #- SPARK_DAEMON_MEMORY=2g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_OPTS="-Dspark.master.rest.enabled=true"
    ports:
      # Spark UI 	
      - '8080:8080'
      # Spark REST API
      - '6066:6066'
      # Spark SUBMIT
      - '7077:7077'
    volumes:
      - ./python:/python
    networks:
      - sparknet  
  spark-worker:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      #- SPARK_WORKER_MEMORY=2g
      #- SPARK_WORKER_CORES=1      
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark 
    volumes:
      - ./python:/python
    networks:
      - sparknet
  livy:
    container_name: livy_server
    hostname: livy_server
    build: ./livy-server/
    command: ["sh", "-c", "/opt/bitnami/livy/bin/livy-server"]
    user: root
    volumes:
      - type: bind
        source: ./livy-server/conf/
        target: /opt/bitnami/livy/conf/
      - type: bind
        source: ./livy-server/target/
        target: /target/
      - type: bind
        source: ./livy-server/data/
        target: /data/
      - type: bind
        source: ./livy-server/logs/
        target: /opt/bitnami/livy/logs/        
    ports:
      - '8998:8998'
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - sparknet
    #deploy:
      #resources:
        #limits:
          #cpus: '0.5'
          #memory: 2g         
networks:
  sparknet:
    driver: bridge      