services:
  spark-master:
    container_name: spark-master
    hostname: spark-master
    build:
      context: ./
      dockerfile: ./spark/Dockerfile
    ports:
      - "80:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_DAEMON_MEMORY=2g
      - SPARK_MASTER_OPTS="-Dspark.master.rest.enabled=true"
      - PYSPARK_PYTHON=python3
    entrypoint: 
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    volumes:
      - ./data:/opt/spark/work-dir/spark-warehouse/data:rw
      - ./python:/python
    networks:
      - sparknet

  spark-worker:
    # reuse the image built for the spark-master
    image: spark-livy-spark-master
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
      - PYSPARK_PYTHON=python3
    depends_on:
      - spark-master
    entrypoint:
      - "bash" 
      - "-c"
      - "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    volumes:
      - ./data:/opt/spark/work-dir/spark-warehouse/data:rw
      - ./python:/python
    networks:
      - sparknet

  livy:
    container_name: livy-server
    hostname: livy-server
    environment:
      - PYSPARK_PYTHON=python3
    build: ./livy-server/
    command: ["sh", "-c", "/opt/livy/bin/livy-server"]
    user: root
    volumes:
      - ./livy-server/conf/:/opt/livy/conf/       
      - ./livy-server/target/:/target/        
      - ./livy-server/data/:/data/       
      - ./livy-server/logs/:/opt/livy/logs/
    ports:
      - '443:8998'
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - sparknet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g

networks:
  sparknet:
    driver: bridge
