# Source: https://github.com/bitnami/containers/tree/main/bitnami/spark#readme

services:
  spark-master:
    image: bitnami/spark:3.4.0
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_DAEMON_MEMORY=4g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_OPTS="-Dspark.master.rest.enabled=true"
    ports:
      # Spark UI 	
      - '8080:8080'
      # Spark REST API
      - '6066:6066'
      # Spark SUBMIT
      - '7077:7077'
    volumes:
      - ./python:/python
    networks:
      - sparknet  
  spark-worker:
    image: bitnami/spark:3.4.0
    container_name: spark-worker
    hostname: spark-worker    
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_CORES=1      
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark 
    volumes:
      - ./python:/python
    depends_on:
      - spark-master      
    networks:
      - sparknet
  livy:
    container_name: livy-server
    hostname: livy-server
    build: ./livy-server/
    command: ["sh", "-c", "/opt/bitnami/livy/bin/livy-server"]
    user: root
    volumes:
      - ./livy-server/conf/:/opt/bitnami/livy/conf/       
      - ./livy-server/target/:/target/        
      - ./livy-server/data/:/data/       
      - ./livy-server/logs/:/opt/bitnami/livy/logs/               
    ports:
      - '8998:8998'
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - sparknet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4g
networks:
  sparknet:
    driver: bridge      
