apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: livy-ingress
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: livy
                port:
                  number: {{ .Values.apacheLivy.livyPort }}
            path: /
            pathType: Prefix
