apiVersion: v1
kind: Service
metadata:
  name: livy
  namespace: {{ .Values.metadata.namespace }}
  labels:
    name: livy
spec:
  ports:
    - name: "{{ .Values.apacheLivy.livyPort }}"
      port: {{ .Values.apacheLivy.livyPort }}
      targetPort: {{ .Values.apacheLivy.targetLivyPort }}
  selector:
    name: livy
  type: {{ .Values.general.serviceType }}
