apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-livy
  namespace: {{ .Values.metadata.namespace }}
  labels:
    role: livy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: livy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        role: livy
    spec:
      containers:
        - args:
            - sh
            - -c
            - /opt/livy/bin/livy-server
          env:
            - name: PYSPARK_PYTHON
              value: python3
          image: {{ .Values.apacheLivy.image }}
          name: livy-server
          ports:
            - containerPort: {{ .Values.apacheLivy.targetLivyPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/livy/conf
              name: livy-configs
            - mountPath: /opt/spark/conf
              name: spark-configs
      hostname: livy-server
      restartPolicy: Always
      volumes:
        - configMap:
            name: livy-configs
          name: livy-configs
        - configMap:
            name: spark-configs
          name: spark-configs
