apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-master-ingress
  namespace: {{ .Values.metadata.namespace }}
spec:
  rules:
  - host: mounir.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /spark
        pathType: Prefix
        backend:
          service:
            name: spark-master
            port:
              number: {{ .Values.sparkMaster.sparkMasterWebuiPort }}
