#https://github.com/marketplace/actions/docker-compose-action
name: Docker Compose Action
on:  
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main    
jobs:
  BuildRunTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: python --version      

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"          

      - name: Check containers
        run: |
          docker ps
          
      - name: Test Spark Submit (Spark)
        run: |
          docker compose exec spark-worker spark-submit --master spark://spark-master:7077 /python/spark-submit/test_spark.py

      - name: Test Spark Submit (Pandas)
        run: |          
          docker compose exec spark-worker spark-submit --master spark://spark-master:7077 /python/spark-submit/test_pandas.py

      - name: Test Apache Livy REST - Start Session
        run: |          
          curl -X POST --data '{"kind": "pyspark", "name": "test pyspark session from python REST API"}' -H "Content-Type: application/json" localhost:8998/sessions

      - name: Wait for 2min to start the session
        run: |
          sleep 120s
          
      - name: Test Apache Livy REST - Run code
        run: |
          curl localhost:8998/sessions/0/statements -X POST -H 'Content-Type: application/json' -d'{"code":"spark.createDataFrame([{\"id\": 1, \"name\": \"Mounir\"}]).show()"}' 

      - name: Test Apache Livy REST - Check statement
        run: |
          curl localhost:8998/sessions/0/statements/0

      - name: Test Apache Livy Python - Start Session
        run: |          
          python /python/livy/start_session.py

      - name: Wait for 2min to start the session
        run: |
          sleep 120s          

      - name: Test Apache Livy Python - Wait for Idle
        run: |          
          python /python/livy/wait_for_idle.py

      - name: Test Apache Livy Python - Run code
        run: |          
          python /python/livy/run_code.py
